version: 2.1

orbs:
  python: cjw296/python-ci@1.2

jobs:
  pip-run-tests:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: "Install mush 3.x"
          command: |
            cd ~
            git clone git@github.com:cjw296/mush.git
            cd mush
            git checkout 3.x
            sudo pip install -e .
      - python/pip-run-tests:
          command: "pytest --cov"

common: &common
  jobs:

    - pip-run-tests:
        name: python36
        image: circleci/python:3.6

    - pip-run-tests:
        name: python37
        image: circleci/python:3.7

    - python/coverage:
        name: coverage
        requires:
          - python36
          - python37

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
